trigger:
- main

pool:
  vmImage: 'ubuntu-latest'

steps:
- task: AzureCLI@2
  displayName: "Verify Azure Service Connection"

  inputs:
    azureSubscription: 'ADO-SVC'
    scriptType: 'bash'
    scriptLocation: 'inlineScript'
    inlineScript: |
      echo "Logged into Azure successfully"

      echo "Current account details:"
      az account show

      echo "Available subscriptions:"
      az account list --output table
